### ISSUE TITLE
bug: not ignoring modifier keys

### ISSUE THREAD

**Issue by antonio-hickey** [antonio-hickey/Typist#11]
## Problem
When a round is started and a user is typing, we are not ignoring modifier keys like shift, ctrl, and alt. There are words that require use of modifiers, and we should also just ignore them in general as they're out of scope in a sense.

## [Demo of the problem](https://typist-seven.vercel.app) (https://typist-seven.vercel.app)
- Click the link above
- Start a round
- Press a modifier key like (shift, ctrl, or alt)
- Notice it detects it as input, it should NOT.

## Proposed  Solution
Add logic to the function which handles a key pressed down (`handleKeyDown` (lines `174` - `194`) in [index.tsx](https://github.com/antonio-hickey/Typist/blob/main/src/pages/index.tsx)) on input, so it ignore's all modifier key codes.

**Comment by HritikR** [comment]
Something like this?
```
const ignoreKeys = [ "Alt", "Shift", "Control" ];
var key = event.which ? event.which : event.key;

// Inside handleKeyDown()
if(!ignoreKeys.includes(key)){
     // Perform task
}

```
